version: "3.8"

services:
  google:
    networks:
      - google
      - local-shared
    build:
      context: src/google
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - PORT=${PORT}
      - DB_MASTER_HOST=${DB_MASTER_HOST}
      - DB_MASTER_USER=${DB_MASTER_USER}
      - DB_MASTER_PASSWORD=${DB_MASTER_PASSWORD}
      - DB_SLAVE_HOST=${DB_SLAVE_HOST}
      - DB_SLAVE_USER=${DB_SLAVE_USER}
      - DB_SLAVE_PASSWORD=${DB_SLAVE_PASSWORD}
      - DB_PORT=3306
      - DB_SCHEMA=mimosa
      - DB_LOG_MODE=${DB_LOG_MODE}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - ASSET_QUEUE_URL=${ASSET_QUEUE_URL}
    ports:
      - "11001:11001"

  asset:
    networks:
      - google
      - local-shared
    build:
      context: src/asset
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=${DEBUG}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - ASSET_QUEUE_NAME=${ASSET_QUEUE_NAME}
      - ASSET_QUEUE_URL=${ASSET_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - GOOGLE_SVC_ADDR=${GOOGLE_SVC_ADDR}
      - GOOGLE_CREDENTIAL_PATH=${GOOGLE_CREDENTIAL_PATH}
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
    ports:
      - "11002:11002"

networks:
  google:
    driver: bridge
    attachable: true
  local-shared:
    external: true
