version: "3.8"

services:
  google:
    networks:
      - google
      - local-shared
    build:
      context: src/google
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - PORT=${PORT}
      - DB_MASTER_HOST=${DB_MASTER_HOST}
      - DB_MASTER_USER=${DB_MASTER_USER}
      - DB_MASTER_PASSWORD=${DB_MASTER_PASSWORD}
      - DB_SLAVE_HOST=${DB_SLAVE_HOST}
      - DB_SLAVE_USER=${DB_SLAVE_USER}
      - DB_SLAVE_PASSWORD=${DB_SLAVE_PASSWORD}
      - DB_PORT=3306
      - DB_SCHEMA=mimosa
      - DB_LOG_MODE=${DB_LOG_MODE}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - ASSET_QUEUE_URL=${ASSET_QUEUE_URL}
      - CLOUD_SPLOIT_QUEUE_URL=${CLOUD_SPLOIT_QUEUE_URL}
      - SCC_QUEUE_URL=${SCC_QUEUE_URL}
      - PORTSCAN_QUEUE_URL=${PORTSCAN_QUEUE_URL}
      - GOOGLE_CREDENTIAL_PATH=${GOOGLE_CREDENTIAL_PATH}
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
    ports:
      - "11001:11001"

  asset:
    networks:
      - google
      - local-shared
    build:
      context: src/asset
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=${DEBUG}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - ASSET_QUEUE_NAME=${ASSET_QUEUE_NAME}
      - ASSET_QUEUE_URL=${ASSET_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - GOOGLE_SVC_ADDR=${GOOGLE_SVC_ADDR}
      - GOOGLE_CREDENTIAL_PATH=${GOOGLE_CREDENTIAL_PATH}
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
      - MAX_NUMBER_OF_MESSAGE=${MAX_NUMBER_OF_MESSAGE}
      - WAIT_MILLI_SEC_PER_REQUEST=${WAIT_MILLI_SEC_PER_REQUEST}
    ports:
      - "11002:11002"

  cloudsploit:
    networks:
      - google
      - local-shared
    build:
      context: src/cloudsploit
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=${DEBUG}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - CLOUD_SPLOIT_QUEUE_NAME=${CLOUD_SPLOIT_QUEUE_NAME}
      - CLOUD_SPLOIT_QUEUE_URL=${CLOUD_SPLOIT_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - GOOGLE_SVC_ADDR=${GOOGLE_SVC_ADDR}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=${GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY}
    ports:
      - "11003:11003"

  scc:
    networks:
      - google
      - local-shared
    build:
      context: src/scc
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=${DEBUG}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - SCC_QUEUE_NAME=${SCC_QUEUE_NAME}
      - SCC_QUEUE_URL=${SCC_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - GOOGLE_SVC_ADDR=${GOOGLE_SVC_ADDR}
      - GOOGLE_CREDENTIAL_PATH=${GOOGLE_CREDENTIAL_PATH}
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
    ports:
      - "11004:11004"

  portscan:
    networks:
      - google
      - local-shared
    build:
      context: src/portscan
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=${DEBUG}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - PORTSCAN_QUEUE_NAME=${PORTSCAN_QUEUE_NAME}
      - PORTSCAN_QUEUE_URL=${PORTSCAN_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - GOOGLE_SVC_ADDR=${GOOGLE_SVC_ADDR}
      - GOOGLE_CREDENTIAL_PATH=${GOOGLE_CREDENTIAL_PATH}
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
      - SCAN_EXCLUDE_PORT_NUMBER=${SCAN_EXCLUDE_PORT_NUMBER}
    ports:
      - "11005:11005"

networks:
  google:
    driver: bridge
    attachable: true
  local-shared:
    external: true
